config/routes.rb
Rails.application.routes.draw do
  root to: 'goods#search'
  get 'goods', to: 'goods#suggest'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/goods_controller.rb
class GoodsController < ApplicationController

  def search
    if params[:keyword].present?
    # if params[:keyword].present? && params[:keyword].gsub(" ","").length >= 2
      @items = RakutenWebService::Ichiba::Item.search(keyword: params[:keyword])
      # binding.pry
    else
      render :search
    end
  end

  def suggest
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goods_helper.rb
module GoodsHelper
end

app/views/goods/_good_list.html.erb
<h1>ここは楽天市場APIを使用しています</h1>
<% if params[:keyword].present? %>
  <div class="lists-wrapper">
    <% @items.first(27).each do |item| %>
      <div class="lists">
        <div class="item-image">
          <%= link_to (image_tag(item.medium_image_urls[0])), item.url %>
        </div>
        <div class="price-outer">
          <div class="price-inner">
            <p> 価格 <%= item.price %> 円 </p>
          </div>
        </div>
        <div class="sub-title">
          <p><%= item.name %></p>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/goods/search.html.erb
<header class="title">
  <h1>Rakuten Search</h1>
</header>

<main>
  <div>楽天が提供しているAPIであれば、上手くいきます。</div>
  <%= link_to "サジェストAPIへ移動する", goods_path %>

  <div class='content'>
    <div id="search-box">
      <%= form_with(url: root_path, local: true, method: :get, class: "search") do |form| %>
        <%= form.text_field :keyword, placeholder: "検索する", class: "search-input" %>
        <%= form.submit "検索", class: "search-btn" %>
      <% end %>
    </div>
    <div id='good_list'>
      <%= render partial: 'good_list' %>
    </div>
  </div>
</main>

app/views/goods/suggest.html.erb
<header class="title">
  <h1>Rakuten Search</h1>
</header>

<body>
  <main>
    <h1>ここで、サジェストのAPIを叩いてます。fetchできないため、ログのみの確認になります。</h1>
    <%= link_to "楽天市場APIへ移動する", root_path %>
    <div id="app">
    </div>
  </main>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rakusearch</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>